name: helloworld
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.3
  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.0
  #身份证拍照
  camera:
  #状态管理
  event_bus: ^1.0.1
  fluro: ^1.3.4
  #选择图片
  image_picker: ^0.6.2+1 #^0.5.4
  photo: ^0.3.4+1
  sqflite: ^1.1.0
  flutter_markdown: ^0.2.0
  #手机上拨打电话
  url_launcher: ^4.0.1
  #toast消息提醒
  fluttertoast: ^3.0.3
  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  flutter_sound: ^1.4.7
  dio: ^2.1.0
#  dio: 1.0.13
  # 极光im
#  jmessage_flutter:
#    git:
#      url: https://github.com/hanjianchun/jmessage-flutter-plugin.git
  jmessage_flutter: ^0.6.3
  # 视频播放
  chewie: ^0.9.6
  video_player: ^0.9.0
  #使用缓存图片
#  flutter_cache_manager: ^0.1.0
  cached_network_image: ^1.1.1
  #富文本
#  flutter_html_textview: ^0.2.6
  flutter_html: ^0.10.4
  flutter_spinkit: ^3.1.0
  #微信SDK
#  fluwx: ^1.0.4
  fluwx: ^1.2.1+2
  #支付宝支付
  tobias: ^1.2.2
  #网页
#  flutter_webview_plugin: ^0.3.11
  flutter_webview_plugin:
    git:
      url: https://github.com/hanjianchun/flutter_webview_plugin.git
  webview_flutter: ^0.3.15+1
  #flutter_picker: ^1.0.11
  #屏幕适配方案
  flutter_screenutil: ^0.4.2
  #省市区三级联动
  city_pickers: ^0.1.16
  # Flutter 城市列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.1
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: 1.1.6
  #二维码扫描
  barcode_scan:
    git:
      url: https://github.com/hanjianchun/flutter_barcode_reader.git
  #地理位置
  amap_base_location: 0.4.0+2
#  amap_location_fluttify: ^0.8.11+481e45c
  #权限管理
  permission_handler: ^3.1.0
  #键盘监听事件
  keyboard_visibility: ^0.5.6
  #压缩图片
  flutter_native_image: ^0.0.4
  #通讯录
#  native_contact_picker: ^0.0.6
  #日期时间选择插件
  flutter_datetime_picker: ^1.2.8
  #二维码生成
  qr_flutter: ^3.0.1
  #图片裁切
  image_cropper: ^1.1.2
  #图片
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  #苹果登录
  apple_sign_in:
    git: https://github.com/hanjianchun/flutter_apple_sign_in.git
  #设备信息
  device_info: ^0.4.0
  #本地通知
#  flutter_local_notifications: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/app.db
  - assets/images/
  - assets/expression/
#  - assets/images/bg_identify_head.png
  - assets/images/bg_identify_idcard.png
#  - assets/images/bg_identify_qrcode.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
     - family: NotoSansSc
       fonts:
         - asset: assets/fonts/pingfang-normal.ttf
     - family: taobaoIconFont
       fonts:
         - asset: assets/fonts/taobao/iconfont.ttf
     - family: wxIconFont
       fonts:
         - asset: assets/fonts/weixin_font/iconfont.ttf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
